### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by FalsoMoralista** [google-research/tf-slim#4]
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
pr2020-01-29 15:18:13.935115: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-01-29 15:18:13.936492: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
>>> **print(tf.__version__)**
**2.1.0**
>>> **import tf_slim as slim**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luciano/.local/lib/python3.6/site-packages/tf_slim/__init__.py", line 23, in <module>
    from tf_slim import evaluation
  File "/home/luciano/.local/lib/python3.6/site-packages/tf_slim/evaluation.py", line 131, in <module>
    from tensorflow.contrib.training.python.training import evaluation
**ModuleNotFoundError: No module named 'tensorflow.contrib'**

Does this repository wasn't created to move the slim away from contrib or am i  mistaken?
Should i install tensorflow 1.14 instead?

**Comment by marksandler2** [comment]
This should now be fixed (perfect timing!)

**Comment by lukacsg** [comment]
+1

**Comment by marksandler2** [comment]
No more mentions of tf.contrib in the entire code base!

**Comment by oopDaniel** [comment]
Thanks for the change! Yet I found the package on PyPI is still the old one, so users would have to do `pip install git+https://github.com/google-research/tf-slim` instead of `pip install tf_slim`.

**Comment by Imranmkt** [comment]
I get the same error when I run ( import tensorflow.contrib.slim as slim). Any idea to figure out?

**Comment by ArimaValanImmanuel** [comment]
> I get the same error when I run ( import tensorflow.contrib.slim as slim). Any idea to figure out?

same for me too

**Comment by marksandler2** [comment]
you need to upgrade tf_slim

**Comment by jianningLuan** [comment]
> you need to upgrade tf_slim

how to upgrade. I already upgrade it but also same error

**Comment by Imranmkt** [comment]
> 

upgrade tf_slim
